#!/usr/bin/env bash
# Cache the terraform outputs the local client needs into .env at the repo root.
#
# The predecessor was a terraform output that composed the whole command, run as
# `eval "$(terraform output -raw chat_command)"`. Three things were wrong with
# it: an output stopped being a fact about AWS and became a claim about this
# machine's layout, which is how abspath() once baked a CI runner's checkout
# path into the state; the command was eval'd; and talking to the agent needed
# an initialised backend and live credentials every single time. A file needs
# them once, and can be handed to someone who has no terraform at all.
#
# .env is a cache, not a source of truth. Rerun this after every apply - the
# runtime ARN changes whenever the runtime is replaced.
set -euo pipefail

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root/infrastructure"

if [ ! -d .terraform ]; then
  echo "infrastructure/ is not initialised; run: (cd infrastructure && terraform init)" >&2
  exit 1
fi

# Captured rather than piped: the merge below arrives on stdin as a program, so
# the data has to travel some other way.
outputs=$(terraform output -json)

OUTPUTS_JSON="$outputs" ENV_FILE="$root/.env" python3 <<'PY'
"""Write .env from the terraform outputs, keeping what was set by hand."""

import json
import os
from pathlib import Path


# Which output feeds which variable. Only the ones something actually reads:
# scripts/chat.py takes the first two, tests/e2e the rest. An output nobody
# reads is a line that can go stale without anyone noticing, so the remaining
# outputs stay a `terraform output` lookup.
FROM_TERRAFORM = {
    "AWS_REGION": "aws_region",
    "AGENT_RUNTIME_ARN": "agent_runtime_arn",
    "GATEWAY_URL": "gateway_url",
    "DYNAMODB_TABLE_NAME": "dynamodb_table_name",
}

# Not an output: this one is the operator's to choose, and two different values
# across two runs are what makes the per-user isolation visible from outside.
DEFAULTS = {"USER_ID": "cli-operator"}

HEADER = [
    "# Generated by scripts/sync_env.sh. Terraform is the source of truth and",
    "# this is a cached copy of it, so regenerate after every apply. A real",
    "# environment variable still wins: USER_ID=bob python scripts/chat.py.",
    "",
]

env_file = Path(os.environ["ENV_FILE"])
outputs = json.loads(os.environ["OUTPUTS_JSON"])

missing = sorted(name for name in FROM_TERRAFORM.values() if name not in outputs)
if missing:
    raise SystemExit(f"terraform has no output {', '.join(missing)}; has the stack been applied?")

# Parsing this file back is parsing our own output - plain KEY=value, no
# quoting, no continuations - which is why a few lines are enough here. Reading
# an arbitrary .env is a different job, and python-dotenv does that one in
# scripts/chat.py.
existing = {}
if env_file.exists():
    for raw in env_file.read_text().splitlines():
        line = raw.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            existing[key.strip()] = value.strip()

kept = {**DEFAULTS, **{key: value for key, value in existing.items() if key not in FROM_TERRAFORM}}

lines = [*HEADER]
lines += [f"{key}={outputs[output]['value']}" for key, output in FROM_TERRAFORM.items()]
lines += ["", "# Yours to edit; a regenerate keeps whatever is set here."]
lines += [f"{key}={value}" for key, value in kept.items()]

env_file.write_text("\n".join(lines) + "\n")
print(f"wrote {env_file} from {len(FROM_TERRAFORM)} terraform outputs")
PY
